name: CI TaskFlow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependencias
      run: dotnet restore TaskFlow.slnx

    - name: Verificar Linting (Estilo do Codigo)
      run: dotnet format TaskFlow.slnx --verify-no-changes

    - name: Compilar o Projeto
      run: dotnet build TaskFlow.slnx --no-restore --configuration Release

    - name: Executar Testes Automatizados
      run: dotnet test TaskFlow.slnx --no-build --configuration Release --verbosity normal
